# mongot.conf
syncSource:
   replicaSet:
      hostAndPort: "mongod.search-community:27017"
      username: "mongotUser"
      passwordFile: "/auth/passwordFile"
      authSource: "admin"
      tls: false
storage:
   dataPath: "/data/mongot"
server:
   grpc:
      address: "mongot:27028"
metrics:
   enabled: true
   address: "mongot:9946"
healthCheck:
   address: "mongot:8080"
logging:
   verbosity: INFO
# Uncomment for auto-embedding configuration
# embedding:
#    queryKeyFile: /auth/voyage-api-query-key
#    indexingKeyFile: /auth/voyage-api-indexing-key
#    providerEndpoint: https://ai.mongodb.com/v1/embeddings # Replace with the following endpoint URL if you created the API key directly from Voyage AI: https://api.voyageai.com/v1/embeddings
#    isAutoEmbeddingViewWriter: true # Designate this as leader instance for writing the automated embedding to the View.
