"""MCP tool surface for agent interaction."""

from memex.mcp.tools import (
    CreateEdgeInput,
    DependenciesInput,
    DeprecateItemInput,
    DreamStateInvokeInput,
    GetEdgesInput,
    GetRevisionsInput,
    ImpactAnalysisInput,
    IngestToolInput,
    ListItemsInput,
    MemexToolService,
    MoveTagInput,
    ProvenanceInput,
    RecallToolInput,
    RerankInput,
    ResolveAsOfInput,
    ResolveByTagInput,
    ResolveTagAtTimeInput,
    ReviseItemInput,
    RollbackTagInput,
    UndeprecateItemInput,
    WorkingMemoryClearInput,
    WorkingMemoryGetInput,
    create_mcp_server,
)

__all__ = [
    "CreateEdgeInput",
    "DependenciesInput",
    "DeprecateItemInput",
    "DreamStateInvokeInput",
    "GetEdgesInput",
    "GetRevisionsInput",
    "ImpactAnalysisInput",
    "IngestToolInput",
    "ListItemsInput",
    "MemexToolService",
    "MoveTagInput",
    "ProvenanceInput",
    "RecallToolInput",
    "RerankInput",
    "ResolveAsOfInput",
    "ResolveByTagInput",
    "ResolveTagAtTimeInput",
    "ReviseItemInput",
    "RollbackTagInput",
    "UndeprecateItemInput",
    "WorkingMemoryClearInput",
    "WorkingMemoryGetInput",
    "create_mcp_server",
]
